version: '2'
services:
  db:
    image: postgres:10.1-alpine
  web:
    container_name: rails
    image: registry.gitlab.com/wahomekevin/build-rails-kit
    command: sh run.sh
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    depends_on:
      - db
